/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.BL;
import BL.Konto;
import BL.KontoBenutzer;
import Observer.Observer;
import javax.swing.JOptionPane;

/**
 *
 * @author johannesriedmueller
 */
public class KontoGUI extends javax.swing.JFrame implements Observer{

    private Konto account = null;
    private final BL bl = new BL();
    public KontoGUI() {
        initComponents();
        liUsers.setModel(bl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmUser = new javax.swing.JPopupMenu();
        miAddUser = new javax.swing.JMenuItem();
        miTest = new javax.swing.JMenuItem();
        pmAccount = new javax.swing.JPopupMenu();
        miAddKonto = new javax.swing.JMenuItem();
        paAccountLabel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liUsers = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taOut = new javax.swing.JTextArea();

        miAddUser.setText("Add User");
        miAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddUserActionPerformed(evt);
            }
        });
        pmUser.add(miAddUser);

        miTest.setText("Perform account test");
        miTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTestActionPerformed(evt);
            }
        });
        pmUser.add(miTest);

        miAddKonto.setText("Add Account");
        miAddKonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddKontoActionPerformed(evt);
            }
        });
        pmAccount.add(miAddKonto);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paAccountLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Account"));
        paAccountLabel.setPreferredSize(new java.awt.Dimension(400, 60));
        paAccountLabel.setLayout(new java.awt.GridLayout(1, 1));
        getContentPane().add(paAccountLabel, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));
        jPanel2.setMinimumSize(new java.awt.Dimension(35, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 300));
        jPanel2.setLayout(new java.awt.BorderLayout());

        liUsers.setComponentPopupMenu(pmUser);
        jScrollPane1.setViewportView(liUsers);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Log-output"));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 200));
        jPanel3.setLayout(new java.awt.BorderLayout());

        taOut.setEditable(false);
        taOut.setColumns(20);
        taOut.setRows(5);
        taOut.setComponentPopupMenu(pmAccount);
        jScrollPane3.setViewportView(taOut);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddUserActionPerformed
        if(account != null){
            String name = JOptionPane.showInputDialog("Please enter the name: ");
            bl.add(new KontoBenutzer(account, name, this));
        }
        else {
            JOptionPane.showMessageDialog(null, "Please add an account first!");
        }
    }//GEN-LAST:event_miAddUserActionPerformed

    private void miTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTestActionPerformed
        bl.performTest(liUsers.getSelectedIndices());
    }//GEN-LAST:event_miTestActionPerformed

    private void miAddKontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddKontoActionPerformed
        if(account == null){
            KontoDialog dialog = new KontoDialog(this, true);
            dialog.setVisible(true);
            if(dialog.isOk()){
                this.account = dialog.getAccount();
                this.paAccountLabel.add(account);
                revalidate();
            }
            
        }
        else{
            JOptionPane.showMessageDialog(null, "The account was added a while ago.. no need to do it again :D");
        }
    }//GEN-LAST:event_miAddKontoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KontoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<KontoBenutzer> liUsers;
    private javax.swing.JMenuItem miAddKonto;
    private javax.swing.JMenuItem miAddUser;
    private javax.swing.JMenuItem miTest;
    private javax.swing.JPanel paAccountLabel;
    private javax.swing.JPopupMenu pmAccount;
    private javax.swing.JPopupMenu pmUser;
    private javax.swing.JTextArea taOut;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String str) {
        taOut.append(str);
    }
}
