/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.BL;
import BL.Konto;
import javax.swing.JOptionPane;

/**
 *
 * @author johannesriedmueller
 */
public class KontoGUI extends javax.swing.JFrame {

    private Konto account = null;
    private BL bl = new BL();
    public KontoGUI() {
        initComponents();
        liAll.setModel(bl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmUser = new javax.swing.JPopupMenu();
        miAddUser = new javax.swing.JMenuItem();
        miTest = new javax.swing.JMenuItem();
        pmAccount = new javax.swing.JPopupMenu();
        miAddKonto = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        laAmount = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liAll = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taOut = new javax.swing.JTextArea();

        miAddUser.setText("Add User");
        miAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddUserActionPerformed(evt);
            }
        });
        pmUser.add(miAddUser);

        miTest.setText("Perform account test");
        miTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTestActionPerformed(evt);
            }
        });
        pmUser.add(miTest);

        miAddKonto.setText("Add Account");
        miAddKonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddKontoActionPerformed(evt);
            }
        });
        pmAccount.add(miAddKonto);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Account"));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 60));
        jPanel1.setLayout(new java.awt.BorderLayout());

        laAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(laAmount, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));
        jPanel2.setMinimumSize(new java.awt.Dimension(35, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 300));
        jPanel2.setLayout(new java.awt.BorderLayout());

        liAll.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        liAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liAllonChangeDir(evt);
            }
        });
        jScrollPane1.setViewportView(liAll);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Log-output"));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 200));
        jPanel3.setLayout(new java.awt.BorderLayout());

        taOut.setColumns(20);
        taOut.setRows(5);
        taOut.setComponentPopupMenu(pmAccount);
        jScrollPane3.setViewportView(taOut);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddUserActionPerformed
        if(account != null){
            String name = JOptionPane.showInputDialog("Please enter the name: ");
        }
        else {
            JOptionPane.showMessageDialog(null, "Please add an account first!");
        }
    }//GEN-LAST:event_miAddUserActionPerformed

    private void miTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTestActionPerformed
        bl.performTest(liUser.getSelectedIndices());
    }//GEN-LAST:event_miTestActionPerformed

    private void miAddKontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddKontoActionPerformed
        if(account == null){
            KontoDialog dialog = new KontoDialog(this, true);
            dialog.setVisible(true);
            if(dialog.isOk()){
                this.account = dialog.getAccount();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "The account was added a while ago.. no need to do it again :D");
        }
    }//GEN-LAST:event_miAddKontoActionPerformed

    private void liAllonChangeDir(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liAllonChangeDir
        if (evt.getClickCount() == 2) {
            String path = bl.getElementAt(liAll.getSelectedIndex()).getAbsolutePath();
            File currDirUpdate = new File(path);
            if (currDirUpdate.isFile()) {
                try{
                    if(!Desktop.isDesktopSupported()){

                    }
                    else{
                        Desktop desktop = Desktop.getDesktop();
                        if(currDirUpdate.exists()){
                            desktop.open(currDirUpdate);
                        }
                    }
                }
                catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"File cannot be opened!");
                }
            } else {
                bl.deleteAll();
                bl.add(currDirUpdate.getAbsolutePath() + "/..");
                for (File file : currDirUpdate.listFiles()) {
                    bl.add(file.getAbsolutePath());
                }
            }
        }
    }//GEN-LAST:event_liAllonChangeDir

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KontoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel laAmount;
    private javax.swing.JList<myFile> liAll;
    private javax.swing.JMenuItem miAddKonto;
    private javax.swing.JMenuItem miAddUser;
    private javax.swing.JMenuItem miTest;
    private javax.swing.JPopupMenu pmAccount;
    private javax.swing.JPopupMenu pmUser;
    private javax.swing.JTextArea taOut;
    // End of variables declaration//GEN-END:variables
}
